export const letterObj = [
    {
        value: "A"
    },
    {
        value: "B"
    },
    {
        value: "C"
    },
    {
        value: "D"
    },
    {
        value: "E"
    },
    {
        value: "F"
    },
    {
        value: "G"
    },
    {
        value: "H"
    },
    {
        value: "I"
    },
    {
        value: "J"
    },
    {
        value: "K"
    },
    {
        value: "L"
    },
    {
        value: "M"
    },
    {
        value: "N"
    },
    {
        value: "O"
    },
    {
        value: "P"
    },
    {
        value: "Q"
    },
    {
        value: "R"
    },
    {
        value: "S"
    },
    {
        value: "T"
    },
    {
        value: "U"
    },
    {
        value: "V"
    },
    {
        value: "W"
    },
    {
        value: "X"
    },
    {
        value: "Y"
    },
    {
        value: "Z"
    }
];
export const languages = [
    {
        lang: "JavaScript",
        backgroundColor: "#F7DF1E",
        color: "#323330"
    },
    {
        lang: "Python",
        backgroundColor: "#3776AB",
        color: "#FFFFFF"
    },
    {
        lang: "PHP",
        backgroundColor: "#777BB4",
        color: "#FFFFFF"
    },
    {
        lang: "HTML",
        backgroundColor: "#E34F26",
        color: "#FFFFFF"
    },
    {
        lang: "CSS",
        backgroundColor: "#1572B6",
        color: "#FFFFFF"
    },
    {
        lang: "C#",
        backgroundColor: "#9B0099",
        color: "#FFFFFF"
    },
    {
        lang: "Java",
        backgroundColor: "#F8981D",
        color: "#333333"
    },
    {
        lang: "Ruby",
        backgroundColor: "#CC342D",
        color: "#FFFFFF"
    },
    {
        lang: "Assembly",
        backgroundColor: "#00599C",
        color: "#FFFFFF"
    }
];
export const winMessagesArray = [
    "You did it! You really saved some programming languages from the fallout🎉🎉🎉🎉",
    "Bravo!!! <br/> You played nice."
];
export const defeatMessagesArray = [
    `Farewell ${
        lostLanguages[Math.floor(lostLanguages.length * Math.random())]
    }`,
    `Its been an honour, ${
        lostLanguages[Math.floor(lostLanguages.length * Math.random())]
    }`,
    `We lost ${
        lostLanguages[Math.floor(lostLanguages.length * Math.random())]
    } today`,
    "It's high time you started learning Assembly."
];
const words = [
    "cyber",
    "degen",
    "crypto",
    "callback",
    "async",
    "vscode",
    "termux",
    "linux",
    "ubuntu",
    "markdown",
    "hacker",
    "vpn",
    "tenzies",
    "xml",
    "ruby",
    "windows",
    "firewall",
    "dns",
    "proxy",
    "web",
    "href",
    "client",
    "server",
    "function",
    "method",
    "class",
    "object",
    "scope",
    "loop",
    "array",
    "variable",
    "constant",
    "string",
    "integer",
    "boolean",
    "float",
    "syntax",
    "error",
    "debug",
    "compile",
    "execute",
    "runtime",
    "library",
    "module",
    "package",
    "script",
    "comment",
    "return",
    "import",
    "export",
    "promise",
    "await",
    "worker",
    "thread",
    "concurrent",
    "parallel",
    "semaphore",
    "mutex",
    "deadlock",
    "route",
    "request",
    "response",
    "state",
    "hook",
    "prop",
    "component",
    "render",
    "router",
    "context",
    "middleware",
    "backend",
    "frontend",
    "fullstack",
    "deploy",
    "build",
    "bundle",
    "cache",
    "session",
    "cookie",
    "localstorage",
    "unit",
    "integration",
    "endtoend",
    "testcase",
    "assertion",
    "coverage",
    "mock",
    "spy",
    "stub",
    "fixture",
    "git",
    "repo",
    "commit",
    "branch",
    "merge",
    "pull",
    "push",
    "clone",
    "fork",
    "rebase",
    "checkout",
    "head",
    "stash",
    "tag",
    "revert",
    "remote",
    "http",
    "https",
    "ftp",
    "smtp",
    "ssh",
    "tcp",
    "udp",
    "ipsec",
    "icmp",
    "ipv4",
    "ipv6",
    "rpc",
    "rest",
    "soap",
    "exploit",
    "malware",
    "phishing",
    "virus",
    "trojan",
    "worm",
    "brute",
    "force",
    "packet",
    "sniffing",
    "zero-day",
    "patch",
    "encrypt",
    "decrypt",
    "cipher",
    "token",
    "audit",
    "sandbox",
    "subnet",
    "gateway",
    "router",
    "switch",
    "hub",
    "modem",
    "isp",
    "bandwidth",
    "latency",
    "throughput",
    "multicast",
    "broadcast",
    "unicast",
    "socket",
    "port",
    "cdn",
    "load",
    "balance",
    "domain",
    "host",
    "vlan",
    "nat",
    "peering",
    "topology",
    "segment",
    "select",
    "insert",
    "update",
    "delete",
    "join",
    "where",
    "group",
    "order",
    "table",
    "index",
    "query",
    "schema",
    "trigger",
    "view",
    "primary",
    "foreign",
    "column",
    "row",
    "commit",
    "rollback",
    "mongo",
    "redis",
    "nosql",
    "document",
    "keyvalue",
    "graph",
    "cluster",
    "shard",
    "replica",
    "datum",
    "model",
    "train",
    "predict",
    "feature",
    "label",
    "vector",
    "matrix",
    "pivot",
    "outlier",
    "bias",
    "clean",
    "pipeline",
    "ingest",
    "visualize",
    "dashboard",
    "aggregate",
    "json",
    "yaml",
    "csv",
    "protobuf",
    "parquet",
    "shell",
    "bash",
    "zsh",
    "kernel",
    "bios",
    "boot",
    "cli",
    "gui",
    "daemon",
    "service",
    "process",
    "thread",
    "io",
    "memory",
    "swap",
    "filesystem",
    "user",
    "group",
    "admin",
    "root",
    "sudo",
    "prompt",
    "pipe",
    "docker",
    "kubernetes",
    "vm",
    "image",
    "container",
    "virtual",
    "hypervisor",
    "isolate",
    "volume",
    "swarm",
    "aws",
    "azure",
    "gcp",
    "iaas",
    "paas",
    "saas",
    "serverless",
    "lambda",
    "ec2",
    "s3",
    "vpc",
    "region",
    "zone",
    "scaling",
    "elastic",
    "cpu",
    "gpu",
    "ram",
    "rom",
    "ssd",
    "hdd",
    "psu",
    "fan",
    "heatsink",
    "pcb",
    "chip",
    "circuit",
    "wire",
    "solder",
    "resistor",
    "diode",
    "led",
    "fuse",
    "bus",
    "slot",
    "port",
    "display",
    "mouse",
    "keyboard",
    "monitor",
    "printer",
    "webcam",
    "scanner",
    "headset",
    "battery",
    "adapter",
    "hub",
    "dongle",
    "projector",
    "joystick",
    "trackpad",
    "byte",
    "bit",
    "clock",
    "cycle",
    "power",
    "signal",
    "analog",
    "digital",
    "parallel",
    "serial",
    "ai",
    "ml",
    "nlp",
    "cv",
    "robot",
    "agent",
    "neural",
    "network",
    "layer",
    "epoch",
    "tensor",
    "model",
    "hyperparameter",
    "gradient",
    "deep",
    "learning",
    "supervised",
    "unsupervised",
    "blockchain",
    "web3",
    "meta",
    "verse",
    "ar",
    "vr",
    "xr",
    "mixed",
    "reality",
    "quantum",
    "cryptography",
    "smart",
    "contract",
    "token",
    "devops",
    "agile",
    "scrum",
    "kanban",
    "sprint",
    "retro",
    "standup",
    "jira",
    "slack",
    "zoom",
    "stackoverflow",
    "github",
    "repository",
    "pipeline",
    "automation"
];
export function getNewWord() {
    const rndmX = Math.floor(Math.random() * words.length);
    return words[rndmX].toUpperCase();
}
